/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -l ConnectedService -c ConnectedServiceInf -a ConnectedServiceAdaptor -p ConnectedServiceProxy ConnectedServiceInf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CONNECTEDSERVICEADAPTOR_H
#define CONNECTEDSERVICEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <QtCore/qcontainerfwd.h>

/*
 * Adaptor class for interface ese.hmi.csif
 */
class ConnectedServiceInf: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "ese.hmi.csif")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"ese.hmi.csif\">\n"
"    <signal name=\"onConnectedChanged\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"signalName\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"value\"/>\n"
"    </signal>\n"
"    <signal name=\"onDigitalKeySettingStatusChanged\">\n"
"      <arg direction=\"out\" type=\"{sssbiiiibbbbbbbb}\" name=\"value\"/>\n"
"      <annotation value=\"srvwrp::ConnectedServiceWrapper::DigitalKeySettingStatus\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"onNetworkResultChanged\">\n"
"      <arg direction=\"out\" type=\"{sssbiiiibbbbbbbb}\" name=\"networkResult\"/>\n"
"      <annotation value=\"srvwrp::ConnectedServiceWrapper::NetworkConnectionResetResult\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"onDCMWaveStatusChanged\">\n"
"      <arg direction=\"out\" type=\"{sssbiiiibbbbbbbb}\" name=\"dcmWaveStatus\"/>\n"
"      <annotation value=\"srvwrp::ConnectedServiceWrapper::DcmWaveStatus\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"onDigitalKeyActiveStatusChanged\">\n"
"      <arg direction=\"out\" type=\"{sssbiiiibbbbbbbb}\" name=\"dcmWaveStatus\"/>\n"
"      <annotation value=\"srvwrp::ConnectedServiceWrapper::DigitalKeyActiveStatus\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"onDigitalKeyResponseResult\">\n"
"      <arg direction=\"out\" type=\"{sssbiiiibbbbbbbb}\" name=\"digKeyRespRes\"/>\n"
"      <annotation value=\"srvwrp::ConnectedServiceWrapper::DigitalKeyResponseResult\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"onCompletedStartOpening\"/>\n"
"    <signal name=\"onInforChanged\">\n"
"      <arg direction=\"out\" type=\"{sssbiiiibbbbbbbb}\" name=\"listConnectedInf\"/>\n"
"      <annotation value=\"QList&lt;srvwrp::ConnectedServiceWrapper::ConnectedInformation&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"onConnectedListChanged\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"conInfList\"/>\n"
"    </signal>\n"
"    <signal name=\"wallpaperDownloadStatusChanged\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"wallDownStt\"/>\n"
"    </signal>\n"
"    <method name=\"requestDeleteDigitalKey\"/>\n"
"    <method name=\"requestGetDigitalKeySettingStatus\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"requestSetDigitalKeySettingStatus\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"digKeySetStt\"/>\n"
"    </method>\n"
"    <method name=\"requestGetDigitalKeyActiveStatus\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"requestSetDigitalKeyActiveStatus\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"digKeySetActStt\"/>\n"
"    </method>\n"
"    <method name=\"requestStartCall\"/>\n"
"    <method name=\"requestEndCall\"/>\n"
"    <method name=\"requestGetConnectedInformations\">\n"
"      <arg direction=\"out\" type=\"a{sssbiiiibbbbbbbb}\"/>\n"
"      <annotation value=\"QList&lt;srvwrp::ConnectedServiceWrapper::ConnectedInformation&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"requestListWallPaperDownload\">\n"
"      <arg direction=\"out\" type=\"a{sssbiiiibbbbbbbb}\"/>\n"
"      <annotation value=\"QList&lt;srvwrp::ConnectedServiceWrapper::ImageDataBase64&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"requestResetNetwork\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ConnectedServiceInf(ConnectedService *parent);
    virtual ~ConnectedServiceInf();

    inline ConnectedService *parent() const
    { return static_cast<ConnectedService *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void requestDeleteDigitalKey();
    void requestEndCall();
    QList<srvwrp::ConnectedServiceWrapper::ConnectedInformation> requestGetConnectedInformations();
    int requestGetDigitalKeyActiveStatus();
    int requestGetDigitalKeySettingStatus();
    QList<srvwrp::ConnectedServiceWrapper::ImageDataBase64> requestListWallPaperDownload();
    int requestResetNetwork();
    void requestSetDigitalKeyActiveStatus(int digKeySetActStt);
    void requestSetDigitalKeySettingStatus(int digKeySetStt);
    void requestStartCall();
Q_SIGNALS: // SIGNALS
    void onCompletedStartOpening();
    void onConnectedChanged(const QString &signalName, const QDBusVariant &value);
    void onConnectedListChanged(const QString &conInfList);
    void onDCMWaveStatusChanged(srvwrp::ConnectedServiceWrapper::DcmWaveStatus dcmWaveStatus);
    void onDigitalKeyActiveStatusChanged(srvwrp::ConnectedServiceWrapper::DigitalKeyActiveStatus dcmWaveStatus);
    void onDigitalKeyResponseResult(srvwrp::ConnectedServiceWrapper::DigitalKeyResponseResult digKeyRespRes);
    void onDigitalKeySettingStatusChanged(srvwrp::ConnectedServiceWrapper::DigitalKeySettingStatus value);
    void onInforChanged(const QList<srvwrp::ConnectedServiceWrapper::ConnectedInformation> &listConnectedInf);
    void onNetworkResultChanged(srvwrp::ConnectedServiceWrapper::NetworkConnectionResetResult networkResult);
    void wallpaperDownloadStatusChanged(int wallDownStt);
};

#endif
