/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -l ConnectedService -c ConnectedServiceInf -a ConnectedServiceAdaptor -p ConnectedServiceProxy ConnectedServiceInf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "ConnectedServiceProxy.h"

/*
 * Implementation of interface class ConnectedServiceInf
 */

ConnectedServiceInf::ConnectedServiceInf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ConnectedServiceInf::~ConnectedServiceInf()
{
}

