/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ACPAgency.xml -a ACPAgencyAdaptor -c ACPAgencyAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ServiceBusAgencyAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

namespace uicommon
{
    ServiceBusAgency::~ServiceBusAgency(){

    }
    /*
     * Implementation of adaptor class ServiceBusAgencyAdaptor
     */

    ServiceBusAgencyAdaptor::ServiceBusAgencyAdaptor(ServiceBusAgency *parent)
        : QDBusAbstractAdaptor(parent)
    {
        // constructor
        setAutoRelaySignals(true);
    }

    ServiceBusAgencyAdaptor::~ServiceBusAgencyAdaptor()
    {
        // destructor
    }
    void ServiceBusAgencyAdaptor::sendData(const QByteArray& data)
    {
        parent()->sendData(data);
    }
}