/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a WifiAdapterAgencyAdaptor -c WifiAdapterAgencyAdaptor -l WifiAdapterAgency WifiAdapterAgency.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "WifiAdapterAgencyAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

namespace uicommon
{

    /*
     * Implementation of adaptor class WifiAdapterAgencyAdaptor
     */

    WifiAdapterAgencyAdaptor::WifiAdapterAgencyAdaptor(WifiAdapterAgency *parent)
        : QDBusAbstractAdaptor(parent)
    {
        // constructor
        setAutoRelaySignals(true);
    }

    WifiAdapterAgencyAdaptor::~WifiAdapterAgencyAdaptor()
    {
        // destructor
    }

    int WifiAdapterAgencyAdaptor::getPower()
    {
        // handle method call ese.hmi.wifiadapter.getPower
        return parent()->getPower();
    }

    QString WifiAdapterAgencyAdaptor::getSSID()
    {
        // handle method call ese.hmi.wifiadapter.getSSID
        return parent()->getSSID();
    }

    bool WifiAdapterAgencyAdaptor::setPower(int status)
    {
        // handle method call ese.hmi.wifiadapter.setPower
        return parent()->setPower(status);
    }

}