/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -V -N -a HMISystemServiceAdapter -l uicommon::HMISystemService -p HMISystemServiceProxy hmisysif.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "HMISystemServiceProxy.h"

namespace uicommon {
    /*
     * Implementation of interface class EseHmiSysInterface
     */

    HMISystemServiceProxy& HMISystemServiceProxy::getInstance()
    {
        static HMISystemServiceProxy singleton("ese.hmi.services","/SystemService",QDBusConnection::sessionBus());

        return singleton;
    }

    HMISystemServiceProxy::HMISystemServiceProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
        : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
    {
    }

    HMISystemServiceProxy::~HMISystemServiceProxy()
    {
    }
}
