/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a ConnectedServiceAdaptor -c ConnectedServiceAdaptor -i ConnectedServiceAgency.h ConnectedServiceInf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ConnectedServiceAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
namespace uicommon {
    /*
    * Implementation of adaptor class ConnectedServiceAdaptor
    */
    ConnectedServiceAdaptor::ConnectedServiceAdaptor(QObject *parent)
        : QDBusAbstractAdaptor(parent)
    {
        // constructor
        setAutoRelaySignals(true);
    }

    ConnectedServiceAdaptor::~ConnectedServiceAdaptor()
    {
        // destructor
    }

    void ConnectedServiceAdaptor::requestDeleteDigitalKey()
    {
        // handle method call ese.hmi.csif.requestDeleteDigitalKey
        QMetaObject::invokeMethod(parent(), "requestDeleteDigitalKey");
    }

    void ConnectedServiceAdaptor::requestEndCall()
    {
        // handle method call ese.hmi.csif.requestEndCall
        QMetaObject::invokeMethod(parent(), "requestEndCall");
    }

    bool ConnectedServiceAdaptor::requestGetDigitalKeyActiveStatus()
    {
        // handle method call ese.hmi.csif.requestGetDigitalKeyActiveStatus
        bool out0;
        QMetaObject::invokeMethod(parent(), "requestGetDigitalKeyActiveStatus", Q_RETURN_ARG(bool, out0));
        return out0;
    }

    bool ConnectedServiceAdaptor::requestGetDigitalKeySettingStatus()
    {
        // handle method call ese.hmi.csif.requestGetDigitalKeySettingStatus
        bool out0;
        QMetaObject::invokeMethod(parent(), "requestGetDigitalKeySettingStatus", Q_RETURN_ARG(bool, out0));
        return out0;
    }

    void ConnectedServiceAdaptor::requestResetNetwork()
    {
        // handle method call ese.hmi.csif.requestResetNetwork
        QMetaObject::invokeMethod(parent(), "requestResetNetwork");
    }

    void ConnectedServiceAdaptor::requestSetDigitalKeySettingStatus(bool digKeySetStt)
    {
        // handle method call ese.hmi.csif.requestSetDigitalKeySettingStatus
        QMetaObject::invokeMethod(parent(), "requestSetDigitalKeySettingStatus", Q_ARG(bool, digKeySetStt));
    }

    void ConnectedServiceAdaptor::requestStartCall()
    {
        // handle method call ese.hmi.csif.requestStartCall
        QMetaObject::invokeMethod(parent(), "requestStartCall");
    }
}
