/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ACPAgency.xml -a ACPAgencyAdaptor -c ACPAgencyAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ACPAGENCYADAPTOR_H
#define ACPAGENCYADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <QtCore/qcontainerfwd.h>
#include "ACPAgency.h"

namespace uicommon
{
    /*
     * Adaptor class for interface ese.hmi.acpagency
     */
    class ACPAgencyAdaptor : public QDBusAbstractAdaptor
    {
        Q_OBJECT
        Q_CLASSINFO("D-Bus Interface", "ese.hmi.acpagency")
        Q_CLASSINFO("D-Bus Introspection", ""
                                           "  <interface name=\"ese.hmi.acpagency\">\n"
                                           "    <signal name=\"onSessionStateChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"oldState\"/>\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"newState\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onUSBConnectionStateChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"oldState\"/>\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"newState\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onWifiConnectionStateChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"oldState\"/>\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"newState\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onBrightnessChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onColorChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onConstractChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onNotifyCarPlayColorValue\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
                                           "      <arg direction=\"out\" type=\"b\" name=\"isDay\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onNotifyCarPlayContrastValue\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
                                           "      <arg direction=\"out\" type=\"b\" name=\"isDay\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onSongPlayTimeChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onSongTotalTimeChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onChannelActive\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"channelType\"/>\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"channelStatus\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onSongInfoChanged\">\n"
                                           "      <arg direction=\"out\" type=\"{sssi}\" name=\"value\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onArtworkInfoChanged\">\n"
                                           "      <arg direction=\"out\" type=\"{iiiis}\" name=\"value\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onShuffleModeChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onRepeatModeChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onPlayingStatusChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
                                           "    </signal>\n"
                                           "    <signal name=\"onSiriStateChanged\">\n"
                                           "      <arg direction=\"out\" type=\"i\" name=\"siriState\"/>\n"
                                           "    </signal>\n"
                                           "    <method name=\"getSessionState\">\n"
                                           "      <arg direction=\"out\" type=\"i\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"setOperationMode\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"mode\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"getBrightness\">\n"
                                           "      <arg direction=\"out\" type=\"i\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"setBrightness\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"setSourceOn\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"b\" name=\"value\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"trackSongCommand\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"previousSong\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"nextSong\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"ipodKeyRelease\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"enjectKeyEvent\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"keyCode\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"keyStatus\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"switchApplication\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"appId\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"cpAppId\"/>\n"
                                           "      <arg direction=\"in\" type=\"b\" name=\"isSessionEnd\"/>\n"
                                           "      <arg direction=\"in\" type=\"b\" name=\"isExitCam\"/>\n"
                                           "      <arg direction=\"in\" type=\"s\" name=\"phoneNum\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"reqCarPlayImageQuality\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"interruptArbitration\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"type\"/>\n"
                                           "      <arg direction=\"in\" type=\"b\" name=\"normalSource\"/>\n"
                                           "      <arg direction=\"in\" type=\"b\" name=\"isEnter\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"setACPContrastStepValue\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"s\" name=\"detail\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"setACPColorStepValue\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"s\" name=\"detail\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"getACPContrastStepValue\">\n"
                                           "      <arg direction=\"out\" type=\"s\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"getACPColorStepValue\">\n"
                                           "      <arg direction=\"out\" type=\"s\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"setVAStatus\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"status\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"getACPDayContrastValue\">\n"
                                           "      <arg direction=\"out\" type=\"i\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"setACPDayContrastValue\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"getACPDayColorValue\">\n"
                                           "      <arg direction=\"out\" type=\"i\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"setACPDayColorValue\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"getACPNightContrastValue\">\n"
                                           "      <arg direction=\"out\" type=\"i\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"setACPNightContrastValue\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"getACPNightColorValue\">\n"
                                           "      <arg direction=\"out\" type=\"i\"/>\n"
                                           "    </method>\n"
                                           "    <method name=\"setACPNightColorValue\">\n"
                                           "      <arg direction=\"out\" type=\"b\"/>\n"
                                           "      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
                                           "    </method>\n"
                                           "  </interface>\n"
                                           "")
    public:
        ACPAgencyAdaptor(ACPAgency *parent);
        inline ACPAgency *parent() const
        {
            return static_cast<ACPAgency *>(QObject::parent());
        }
        virtual ~ACPAgencyAdaptor();

    public:         // PROPERTIES
    public Q_SLOTS: // METHODS
        int getBrightness();
        int getSessionState();
        bool setBrightness(int value);
        bool setOperationMode(int mode);
        bool setSourceOn(bool value);
        bool trackSongCommand(int value);
        bool previousSong();
        bool nextSong();
        bool ipodKeyRelease();
        bool enjectKeyEvent(int keyCode, int keyStatus);
        
        bool switchApplication(int appId, int cpAppId ,bool isSessionEnd,bool isExitCam,QString phoneNum);
        bool reqCarPlayImageQuality();
        bool interruptArbitration(int type, bool normalSource, bool isEnter);
        bool setACPContrastStepValue(QString detail);
        bool setACPColorStepValue(QString detail);
        QString getACPContrastStepValue();
        QString getACPColorStepValue();
        bool setVAStatus(int status);


        int  getACPDayContrastValue();
        bool setACPDayContrastValue(int value);
        int  getACPDayColorValue();
        bool setACPDayColorValue(int value);
        int  getACPNightContrastValue();
        bool setACPNightContrastValue(int value);
        int  getACPNightColorValue();
        bool setACPNightColorValue(int value);

    Q_SIGNALS: // SIGNALS
        void onBrightnessChanged(int value);
        void onColorChanged(int value);
        void onConstractChanged(int value);
        void onSessionStateChanged(int oldState, int newState);
        void onUSBConnectionStateChanged(int oldState, int newState);
        void onWifiConnectionStateChanged(int oldState, int newState);
        void onChannelActive(int channelType, int channelStatus);
        void onSongInfoChanged(uicommon::ACPAgency::SongInfo songInfo);
        void onArtworkInfoChanged(uicommon::ACPAgency::ArtworkData artworkData);
        void onShuffleModeChanged(int value);
        void onRepeatModeChanged(int value);
        void onPlayingStatusChanged(int value);
        void onSiriStateChanged(int siriState);
        void onSongTotalTimeChanged(int value);
        void onSongPlayTimeChanged(int value);
        void onNotifyCarPlayColorValue(int value, bool isDay);
        void onNotifyCarPlayContrastValue(int value, bool isDay);
    };
}

#endif
