/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp naviboxui.xml -i naviboxui.h -a NaviboxUIAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NAVIBOXUIADAPTOR_H
#define NAVIBOXUIADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "naviboxui.h"
#include <QtCore/qcontainerfwd.h>

/*
 * Adaptor class for interface ese.hmi.naviboxui
 */
class NaviboxUIAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "ese.hmi.naviboxui")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"ese.hmi.naviboxui\">\n"
"    <signal name=\"acceptTransition\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"appid\"/>\n"
"    </signal>\n"
"    <signal name=\"mediaTypeChanged\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"type\"/>\n"
"    </signal>\n"
"    <method name=\"requestTransition\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appid\"/>\n"
"    </method>\n"
"    <method name=\"notifyState\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appid\"/>\n"
"      <arg direction=\"in\" type=\"(i)\" name=\"state\"/>\n"
"      <annotation value=\"NaviboxUIState\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"    </method>\n"
"    <method name=\"changeMediaType\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"setCurrentApp\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appid\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    NaviboxUIAdaptor(QObject *parent);
    virtual ~NaviboxUIAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void changeMediaType(const QString &type);
    void notifyState(const QString &appid, NaviboxUIState state);
    void requestTransition(const QString &appid);
    void setCurrentApp(const QString &appid);
Q_SIGNALS: // SIGNALS
    void acceptTransition(const QString &appid);
    void mediaTypeChanged(const QString &type);
};

#endif
