/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp navigationservice.xml -i navigationservice.h -a NavigationServiceAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NAVIGATIONSERVICEADAPTOR_H
#define NAVIGATIONSERVICEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "navigationservice.h"
#include <QtCore/qcontainerfwd.h>

/*
 * Adaptor class for interface ese.hmi.navigationservice
 */
class NavigationserviceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "ese.hmi.navigationservice")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"ese.hmi.navigationservice\">\n"
"    <signal name=\"screenLayoutChanged\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"config\"/>\n"
"    </signal>\n"
"    <signal name=\"adaptorDataReceived\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"str\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"var\"/>\n"
"    </signal>\n"
"    <signal name=\"adaptorNotified\">\n"
"      <arg direction=\"out\" type=\"(q)\" name=\"type\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"var\"/>\n"
"      <annotation value=\"NavigationIPCType\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"proxyPrivateNotifed\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"(y)\" name=\"proxyType\"/>\n"
"      <arg direction=\"out\" type=\"(q)\" name=\"type\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"var\"/>\n"
"      <annotation value=\"NavigationProxyType\" name=\"org.qtproject.QtDBus.QtTypeName.Out1\"/>\n"
"      <annotation value=\"NavigationIPCType\" name=\"org.qtproject.QtDBus.QtTypeName.Out2\"/>\n"
"    </signal>\n"
"    <signal name=\"popupInfoPrivateNotified\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"(y)\" name=\"proxyType\"/>\n"
"      <arg direction=\"out\" type=\"(q)\" name=\"type\"/>\n"
"      <arg direction=\"out\" type=\"(iiiiiiisssbissbbb)\" name=\"info\"/>\n"
"      <annotation value=\"NavigationProxyType\" name=\"org.qtproject.QtDBus.QtTypeName.Out1\"/>\n"
"      <annotation value=\"NavigationIPCType\" name=\"org.qtproject.QtDBus.QtTypeName.Out2\"/>\n"
"      <annotation value=\"PopupInfo\" name=\"org.qtproject.QtDBus.QtTypeName.Out3\"/>\n"
"    </signal>\n"
"    <signal name=\"popupResultPrivateNotified\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"(y)\" name=\"proxyType\"/>\n"
"      <arg direction=\"out\" type=\"(q)\" name=\"type\"/>\n"
"      <arg direction=\"out\" type=\"(iiiiiii)\" name=\"result\"/>\n"
"      <annotation value=\"NavigationProxyType\" name=\"org.qtproject.QtDBus.QtTypeName.Out1\"/>\n"
"      <annotation value=\"NavigationIPCType\" name=\"org.qtproject.QtDBus.QtTypeName.Out2\"/>\n"
"      <annotation value=\"PopupResult\" name=\"org.qtproject.QtDBus.QtTypeName.Out3\"/>\n"
"    </signal>\n"
"    <signal name=\"naviShowOnMeter\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"naviType\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"indexOnMeter\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"statusLDD\"/>\n"
"    </signal>\n"
"    <signal name=\"meterTypeChanged\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"type\"/>\n"
"    </signal>\n"
"    <method name=\"showNaviApp\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"dispType\"/>\n"
"      <annotation value=\"HMIScreenType\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"hideNaviApp\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <annotation value=\"HMIScreenType\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"sendPopupRespDisp\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"featureId\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"popupId\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"sendDtvPopupRespDisp\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"featureId\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"popupId\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"sendProxyData\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"str\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"var\"/>\n"
"    </method>\n"
"    <method name=\"sendDataToAdaptor\">\n"
"      <arg direction=\"in\" type=\"(q)\" name=\"type\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"var\"/>\n"
"      <annotation value=\"NavigationIPCType\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"sendDataToAdaptor\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"(y)\" name=\"proxyType\"/>\n"
"      <arg direction=\"in\" type=\"(q)\" name=\"type\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"var\"/>\n"
"      <annotation value=\"NavigationProxyType\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <annotation value=\"NavigationIPCType\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"    </method>\n"
"    <method name=\"sendDataToAdaptor\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"(y)\" name=\"proxyType\"/>\n"
"      <arg direction=\"in\" type=\"(q)\" name=\"type\"/>\n"
"      <arg direction=\"in\" type=\"(iiiiiiisssbissbbb)\" name=\"info\"/>\n"
"      <annotation value=\"NavigationProxyType\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <annotation value=\"NavigationIPCType\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"      <annotation value=\"PopupInfo\" name=\"org.qtproject.QtDBus.QtTypeName.In3\"/>\n"
"    </method>\n"
"    <method name=\"sendDataToAdaptor\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"(y)\" name=\"proxyType\"/>\n"
"      <arg direction=\"in\" type=\"(q)\" name=\"type\"/>\n"
"      <arg direction=\"in\" type=\"(iiiiiii)\" name=\"result\"/>\n"
"      <annotation value=\"NavigationProxyType\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <annotation value=\"NavigationIPCType\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"      <annotation value=\"PopupResult\" name=\"org.qtproject.QtDBus.QtTypeName.In3\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")

public:
    NavigationserviceAdaptor(NavigationService *parent);
    virtual ~NavigationserviceAdaptor();

    inline NavigationService *parent() const { return static_cast<NavigationService *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void showNaviApp(const QString& appId, int dispType);
    void hideNaviApp(const QString& appId);
    void sendPopupRespDisp(int featureId, int popupId, int status);
    //Temporary
    void sendDtvPopupRespDisp(int featureId, int popupId, int status);
    //
    void sendProxyData(const QString &str, const QDBusVariant &var);
    void sendDataToAdaptor(const NavigationIPCType type, const QDBusVariant& var);
    void sendDataToAdaptor(const uint id, const NavigationProxyType proxyType, const NavigationIPCType type, const QDBusVariant& var);
    void sendDataToAdaptor(const uint id, const NavigationProxyType proxyType, const NavigationIPCType type, const PopupInfo& info);
    void sendDataToAdaptor(const uint id, const NavigationProxyType proxyType, const NavigationIPCType type, const PopupResult& result);
Q_SIGNALS: // SIGNALS
    void adaptorDataReceived(const QString &str, const QDBusVariant &var);
    void screenLayoutChanged(const QString &config);
    void adaptorNotified(const NavigationIPCType type, const QDBusVariant& var);
    void proxyPrivateNotifed(const uint id, const NavigationProxyType proxyType, const NavigationIPCType type, const QDBusVariant& var);
    void popupInfoPrivateNotified(const uint id, const NavigationProxyType proxyType, const NavigationIPCType type, const PopupInfo& test);
    void popupResultPrivateNotified(const uint id, const NavigationProxyType proxyType, const NavigationIPCType type, const PopupResult& result);
    void naviShowOnMeter(const QString& naviType, const int& indexOnMeter,const bool& statusLDD);
    void meterTypeChanged(const int& type);
};

#endif
