/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp touchservice.xml -i touchservice.h -a TouchAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TOUCHSERVICEADAPTOR_H
#define TOUCHSERVICEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "touchservice.h"
#include <QtCore/qcontainerfwd.h>

/*
 * Adaptor class for interface local.TouchService
 */
class TouchServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "ese.hmi.TouchService")
    Q_CLASSINFO("D-Bus Introspection", ""
"   <interface name=\"ese.hmi.TouchService\">\n"
"       <method name=\"sendTouch\">\n"
"           <arg direction=\"in\" type=\"(ia(iidddd))\" name=\"info\"/>\n"
"           <annotation value=\"TouchInfo\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"       </method>\n"
"   </interface>\n"
        "")
public:
    TouchServiceAdaptor(QObject *parent);
    virtual ~TouchServiceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void sendTouch(TouchInfo info);
Q_SIGNALS: // SIGNALS
};

#endif
