/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp touchservice.xml -i touchservice.h -a TouchAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "TouchServiceAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TouchServiceAdaptor
 */

TouchServiceAdaptor::TouchServiceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TouchServiceAdaptor::~TouchServiceAdaptor()
{
    // destructor
}

void TouchServiceAdaptor::sendTouch(TouchInfo info)
{
    // handle method call local.TouchService.sendTouch
    QMetaObject::invokeMethod(parent(), "sendTouch", Q_ARG(TouchInfo, info));
}
