/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp virtualassistantservice.xml -i virtualassistantservice.h -a VirtualAssistantAdaptor.
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "VirtualAssistantAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class VirtualAssistantAdaptor
 */

VirtualAssistantAdaptor::VirtualAssistantAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

VirtualAssistantAdaptor::~VirtualAssistantAdaptor()
{
    // destructor
}

void VirtualAssistantAdaptor::sendCommand(VAComand command, const QDBusVariant& data)
{
    // handle method call ese.hmi.VirtualAssistantService.sendCommand
    QMetaObject::invokeMethod(parent(), "sendCommand", Q_ARG(VAComand, command), Q_ARG(QDBusVariant, data));
}

