/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp virtualassistantservice.xml -i virtualassistantservice.h -a VirtualAssistantAdaptor.
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VIRTUALASSISTANTADAPTOR__H
#define VIRTUALASSISTANTADAPTOR__H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "virtualassistantservice.h"
#include <QtCore/qcontainerfwd.h>

/*
 * Adaptor class for interface ese.hmi.VirtualAssistantService
 */
class VirtualAssistantAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "ese.hmi.VirtualAssistantService")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"ese.hmi.VirtualAssistantService\">\n"
"    <method name=\"sendCommand\">\n"
"      <arg direction=\"in\" type=\"(i)\" name=\"command\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"data\"/>\n"
"      <annotation value=\"VAComand\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    VirtualAssistantAdaptor(QObject *parent);
    virtual ~VirtualAssistantAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void sendCommand(VAComand command, const QDBusVariant& data);
Q_SIGNALS: // SIGNALS
};

#endif
