/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -l SmartPhoneAgency -c SmartPhoneAgencyAdaptor -a SmartPhoneAgencyAdaptor SmartPhoneAgency.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "SmartPhoneAgencyAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

namespace uicommon
{

    /*
     * Implementation of adaptor class SmartPhoneAgencyAdaptor
     */

    SmartPhoneAgencyAdaptor::SmartPhoneAgencyAdaptor(SmartPhoneAgency *parent)
        : QDBusAbstractAdaptor(parent)
    {
        // constructor
        setAutoRelaySignals(true);
    }

    SmartPhoneAgencyAdaptor::~SmartPhoneAgencyAdaptor()
    {
        // destructor
    }

    bool SmartPhoneAgencyAdaptor::getCurrentSession(uicommon::SmartPhoneAgency::DeviceInfo &retValue)
    {
        // handle method call ese.hmi.smartphoneagency.getCurrentSession
        return parent()->getCurrentSession(retValue);
    }

    QList<uicommon::SmartPhoneAgency::DeviceInfo> SmartPhoneAgencyAdaptor::getDeviceList()
    {
        // handle method call ese.hmi.smartphoneagency.getDeviceList
        return parent()->getDeviceList();
    }

    bool SmartPhoneAgencyAdaptor::getUSBDevice(uicommon::SmartPhoneAgency::DeviceInfo &retValue)
    {
        // handle method call ese.hmi.smartphoneagency.getUSBDevice
        return parent()->getUSBDevice(retValue);
    }

    bool SmartPhoneAgencyAdaptor::isExisting(const QString &serialNum, const QString &btAddr)
    {
        // handle method call ese.hmi.smartphoneagency.isExisting
        return parent()->isExisting(serialNum, btAddr);
    }

    int SmartPhoneAgencyAdaptor::startSession(const QString &btAddr, int devType, int type, int entrance)
    {
        // handle method call ese.hmi.smartphoneagency.startSession
        return parent()->startSession(btAddr, devType, type, entrance);
    }

    int SmartPhoneAgencyAdaptor::stopSession(const QString &btAddr, int devType, int type, int entrance)
    {
        // handle method call ese.hmi.smartphoneagency.stopSession
        return parent()->stopSession(btAddr, devType, type, entrance);
    }

    bool SmartPhoneAgencyAdaptor::devListRequest()
    {
        return parent()->devListRequest();
    }
}
